import { ObjTy } from '~/common';
export declare const useCommonExample: () => {
    totalPage: import("vue").Ref<number>;
    searchForm: import("vue").Ref<ObjTy>;
    fileList: import("vue").Ref<any[]>;
    chooseFileName: import("vue").Ref<string>;
    commonValue: import("vue").Ref<string>;
    modalShowTitle: import("vue").Ref<string>;
    VITE_APP_IMAGE_URL_PRE: import("vue").Ref<string>;
    VITE_APP_BASE_URL: import("vue").Ref<string>;
    VITE_APP_BASE_WS_URL: import("vue").Ref<string>;
    accessToken: import("vue").Ref<string>;
    userBaseInfo: import("vue").Ref<ObjTy>;
    startEndArr: import("vue").Ref<ObjTy>;
    todayTime: import("vue").Ref<string>;
    currentTime: import("vue").Ref<string>;
    todayTimeLast: import("vue").Ref<string>;
    yesterdayTime: import("vue").Ref<string>;
    beforeThreeDateTime: import("vue").Ref<string>;
    sleep: (time: number) => Promise<null>;
};
export declare const useCommon: () => {
    totalPage: import("vue").Ref<number>;
    searchForm: import("vue").Ref<ObjTy>;
    fileList: import("vue").Ref<any[]>;
    chooseFileName: import("vue").Ref<string>;
    commonValue: import("vue").Ref<string>;
    modalShowTitle: import("vue").Ref<string>;
    VITE_APP_IMAGE_URL_PRE: import("vue").Ref<string>;
    VITE_APP_BASE_URL: import("vue").Ref<string>;
    VITE_APP_BASE_WS_URL: import("vue").Ref<string>;
    accessToken: import("vue").Ref<string>;
    userBaseInfo: import("vue").Ref<ObjTy>;
    startEndArr: import("vue").Ref<ObjTy>;
    todayTime: import("vue").Ref<string>;
    currentTime: import("vue").Ref<string>;
    todayTimeLast: import("vue").Ref<string>;
    yesterdayTime: import("vue").Ref<string>;
    beforeThreeDateTime: import("vue").Ref<string>;
    sleep: (time: number) => Promise<null>;
};
export default useCommonExample;
