#!/bin/sh
#. "$(dirname "$0")/_/husky.sh"
#yarn run lint
#npx --no-install commitlint --edit "$1"
#npx husky add .husky/commit-msg 'npx --no-install commitlint --edit "$1"'
#推送之前运行eslint检查
npm  run lint

#推送之前运行tsc检查
#npm run tsc-check


#测试提交有问题阻断
#echo exit;;
